services:
  - type: web
    name: tomorrow-me-backend
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: CORS_ORIGINS
        value: "*"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
